[package]
name = "eots"
description = "EOTS (Extractable One Time Signature) utilities"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish           = true

[dependencies]
hex         = { workspace = true }
k256        = { workspace = true }
rand        = { workspace = true, optional = true }
sha2        = { workspace = true }
thiserror   = { workspace = true }

[dev-dependencies]
babylon-test-utils = { path = "../../packages/test-utils" }
rand               = { workspace = true }

[features]
rand = ["dep:rand"]
