[package]
name              = "babylon-btcstaking"
description       = "BTC staking library in Rust"
version.workspace = true
edition.workspace = true

[dependencies]
bitcoin         = { workspace = true }
digest          = { workspace = true }
rust_decimal    = { workspace = true }
hex             = { workspace = true }
sha2            = { workspace = true }
k256            = { workspace = true }
thiserror       = { workspace = true }
eots            = { path = "../eots" }
babylon-schnorr-adaptor-signature = { path = "../schnorr-adaptor-signature" }

[dev-dependencies]
babylon-proto      = { workspace = true }
babylon-test-utils = { path = "../test-utils" }
prost              = { workspace = true }
