[package]
name = "babylon-proto"
description = "Babylon protobuf bindings"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

exclude = [ "babylon" ]

[lib]
doctest = false

[dependencies]
bitcoin           = { workspace = true }
bitvec            = { workspace = true }
cosmos-sdk-proto  = { workspace = true }
pbjson-types      = { workspace = true }
prost             = { workspace = true }
sha2              = { workspace = true }
tendermint-proto  = { workspace = true }
