[package]
name = "babylon-apis"
description = "Babylon APIs for BSN staking integration"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
babylon-merkle   = { path = "../merkle", version = "0.15.0" }
babylon-proto    = { path = "../proto", version = "0.15.0" }
bech32           = { workspace = true }
bitcoin          = { workspace = true }
cosmwasm-std     = { workspace = true }
cosmwasm-schema  = { workspace = true }
hex              = { workspace = true }
thiserror        = { workspace = true }
sha2             = { workspace = true }
