[package]
name = "babylon-bindings-test"
description = "Multitest (and other test helpers) support for Babylon-specific contracts"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
anyhow           = { workspace = true }
cosmwasm-std     = { workspace = true }
cw-multi-test    = { workspace = true }
cw-storage-plus  = { workspace = true }
thiserror        = { workspace = true }
schemars         = { workspace = true }
serde            = { workspace = true }
