[package]
name = "babylon-bitcoin"
description = "A wrapper of the rust-bitcoin library"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish           = true

[dependencies]
bitcoin      = { workspace = true, features = ["serde"] }
digest       = { workspace = true }
sha2         = { workspace = true }
serde        = { workspace = true }
schemars     = { workspace = true }
cosmwasm-std = { workspace = true }
k256         = { workspace = true }
thiserror    = { workspace = true }

[dev-dependencies]
hex          = { workspace = true }
