[package]
name = "babylon-test-utils"
description = "Utilities used in Babylon contracts tests"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish           = true

[dependencies]
babylon-apis     = { path = "../apis", version = "0.14.0" }
babylon-proto    = { path = "../proto", version = "0.14.0" }
babylon-bitcoin  = { path = "../bitcoin", version = "0.14.0" }
bitcoin          = { workspace = true }
cosmwasm-std     = { workspace = true }
hex              = { workspace = true }
k256             = { workspace = true }
prost            = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }
