[package]
name = "babylon-merkle"
description = "CometBFT compatible Merkle proofs"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
cosmwasm-schema  = { workspace = true }
cosmwasm-std     = { workspace = true }

sha2             = { workspace = true }
tendermint-proto = { workspace = true }
thiserror        = { workspace = true }

[dev-dependencies]
hex              = { workspace = true }
