name: Local Tests

on:
  workflow_dispatch:
  push:
    branches: [ "xlc/upgrade-datagen-v3" ]
  pull_request:
    branches:
      - '**'
permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-schema-binary-naming:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Check schema binary naming convention
      run: bash scripts/check-schema-naming.sh

  check-go-datagen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.23'
      - name: "Tidy go modules"
        run: go mod tidy
        working-directory: ./datagen
      - name: "Check datagen"
        run: go run datagen/*.go

  local-build-test:
    runs-on: ubuntu-latest
    container:
      image: rust:1.86.0
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Build contracts, check formats, and run unit tests
      run: cargo test --lib

  local-build-test-full-validation:
    runs-on: ubuntu-latest
    container:
      image: rust:1.86.0
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Build contracts, check formats, and run unit tests (full validation)
      run: |
        rustup component add rustfmt clippy
        - name: "Run rustfmt"
        run: cargo fmt --all -- --check
